### ISSUE TITLE
fmt library suggestion

### ISSUE THREAD

**Issue by rh101** [adxeproject/adxe#434]
I noticed you have added the fmt library recently, and in `thirdparty/CMakeLists.txt` this was added:

```
target_include_directories(thirdparty INTERFACE "fmtlib/include")
target_compile_definitions(thirdparty INTERFACE FMT_HEADER_ONLY=1)
```

Just as an alternative, you can keep the entire fmt release as it is (folder name fmt with entire folder structure as it is in their repository), and add this instead:

```
add_subdirectory(fmt)
target_link_libraries(thirdparty fmt-header-only)
target_include_directories(thirdparty INTERFACE "fmt/include")
```

![image](https://user-images.githubusercontent.com/8603230/126054902-c6fcdaed-5481-4458-b4d7-d46d0730afff.png)

The other reason is that it will allow other libraries in a game project to link against `fmt-header-only` as well, otherwise they would need to link against `thirdparty`, which wouldn't make them very portable, since those libraries may be used in non-ADXE projects as well. 

I can submit a PR with the changes if you want me to.

**Comment by halx99** [comment]
Absolutely agree, you can send a pr, and maybe only needs include,src,CMakeLists.txt, README.rst,LICENSE.rst

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: RH ***@***.***>
Sent: Sunday, July 18, 2021 11:45:05 AM
To: adxeproject/adxe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adxeproject/adxe] fmt library suggestion (#434)


I noticed you have added the fmt library recently, and in thirdparty/CMakeLists.txt this was added:

target_include_directories(thirdparty INTERFACE "fmtlib/include")
target_compile_definitions(thirdparty INTERFACE FMT_HEADER_ONLY=1)


Just as an alternative, you can keep the entire fmt release as it is (folder name fmt with entire folder structure as it is in their repository), and add this instead:

add_subdirectory(fmt)
target_link_libraries(thirdparty fmt-header-only)
target_include_directories(thirdparty INTERFACE "fmt/include")
)


That way you can just keep the entire folder structure of fmt as it is, without just copying the include folder on any future updates.

[image]<https://user-images.githubusercontent.com/8603230/126054902-c6fcdaed-5481-4458-b4d7-d46d0730afff.png>

The other reason is that it will allow other libraries in a game project to link against fmt-header-only as well, otherwise they would need to link against thirdparty, which wouldn't make them very portable, since those libraries may be used in other non-ADXE projects as well.

I can submit a PR if you want me to with the changes.

**Comment by rh101** [comment]
Excellent! I'll have a PR ready soon.

**Comment by rh101** [comment]
@halx99 The "support" folder and "ChangeLog.rst" are also required otherwise the cmake fails, but I've removed all other folders that aren't used.
