### ISSUE TITLE
[macOS/iOS] Cannot find assets in Resources without regenerating cmake

### ISSUE THREAD

**Issue by skyventuree** [adxeproject/adxe#606]
How can I import a new asset into the `Resources` folder without having to regenerate cmake every time?
From issue #524, this can only applied to Windows and not macOS, and I don't have experience with CMake so it is hard for me to make changes to it.

- adxe version: 1.0.0b6
- devices test on: iPhone 8 Plus
- developing environments
   - NDK version: N/A
   - Xcode version: 13.3
   - VS/msvctools version: N/A
   - cmake version: 3.22.3
Steps to Reproduce:
1. Import a new file into `Resources`.
2. Load them in the CPP file.
3. File happens to be not found even it is there.

**Comment by DelinWorks** [comment]
I think when you regenerate cmake it executes a script where it moves all the contents of resources folder that's in the project to the release path, I'm on windows so I can't say a solid thing about macos because I have no experience with it, You could make a python script or steal the script in cmake that moves the folder to the release directory, Again in the end I don't know anything about building on mac and that's just a speculation

**Comment by rh101** [comment]
@DelinWorks That doesn't happen for the iOS builds, and probably also the Mac builds.

@skyventuree Issue #524 was specific to Windows.  There is nothing to change in CMake files (like `CMakeLists.txt`) when you add resources.  If anything you just have to run the CMake command again, since the XCode project files may need to be updated with references to the resources, so it's an Xcode requirement, and not an issue with CMake.

You can make it easier on yourself if you create a shell script to add to the root folder of your project, which you run each time you update source files or resource files.  

For example, this creates the folder `build-ios` with the Xcode project configured for real device builds:
```
DIR="./build-ios"
if [ ! -d "$DIR" ]; then
  mkdir -p "$DIR"
fi

cd "$DIR"
cmake .. -GXcode -DCMAKE_TOOLCHAIN_FILE=../core/cmake/ios.mini.cmake -DCMAKE_OSX_ARCHITECTURES=arm64
```

For simulator builds, you would need to replace `-DCMAKE_OSX_ARCHITECTURES=arm64` with `-DCMAKE_OSX_ARCHITECTURES=x86_64`, so probably best to have two different shell scripts, one for real device builds, and the other for simulator builds, such as:

```
DIR="./build-ios-sim"
if [ ! -d "$DIR" ]; then
  mkdir -p "$DIR"
fi

cd "$DIR"
cmake .. -GXcode -DCMAKE_TOOLCHAIN_FILE=../cocos2d/cmake/ios.mini.cmake -DCMAKE_OSX_ARCHITECTURES=x86_64
```
The above creates a `build-ios-sim` folder with the XCode project configured for simulator builds.
