### ISSUE TITLE
Resources Folder Not Being Added to Search Path By Default [Windows]

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#611]
- adxe version: v1.0.0 beta6
- devices tested on: Windows

This bug happens on Windows, The bug is that the resources folder doesn't get added to the search paths by default when running the game from bin folder and NOT from visual studio, the game crashes since it doesn't find the files in resources because the game wasn't told to look for those files in the resources folder.

Steps to Reproduce:
1. Create a project 
2. Build the project for Windows (x32 or x64)
3. Run the executable from bin/debug or release NOT from visual studio
4. The executable will not run because it didn't find the HelloWorld texture because resources folder wasn't added to the search paths in FileUtils class

For now I fix this by adding `FileUtils::getInstance()->addSearchPath("resources");` to my appdelegate class
It's a viable solution but wasn't it supposed to be added from the beginning by default? (it bugged me for hours btw 🙂)

**Comment by rh101** [comment]
You can't do that anymore without copying the binary and the *contents* of resources into the same folder, due to the changes introduced here: [https://github.com/adxeproject/adxe/commit/bbd3a78ae409e2b3bae123a30b0894c99eb3dc3a](https://github.com/adxeproject/adxe/commit/bbd3a78ae409e2b3bae123a30b0894c99eb3dc3a)

It's a little inconvenient now, since sometimes you may want to run multiple instances of the game for testing, and the quickest way to do that previously was to run the executable file directly in the build output folder. The only way to do that now is to have the binaries and resources copied into another directory together.

**Comment by DelinWorks** [comment]
So if i inderstand correctly, i have to move the exe inside resources IF i were not to add a seqrch path? why would init remove resources in the first place?

**Comment by rh101** [comment]
> i have to move the exe inside resources IF i were to not add a search path?

Yes, unfortunately.  It's also what you need to do in order to release your game for distribution.  The "Resource" folder contents sit at the same level as the binaries.

> why would init remove resources in the first place?

I'm not entirely sure why it was changed to this behavior, but that's something @halx99 would have an insight into.

**Comment by halx99** [comment]
Just use visual studio or run.bat in project root to start your game.

**Comment by halx99** [comment]
https://github.com/adxeproject/adxe/blob/dev/templates/cpp-template-default/run.bat.in

**Comment by rh101** [comment]
I must have missed that change to the template project, and it does solve the problem. Thanks @halx99

**Comment by DelinWorks** [comment]
@halx99 @rh101 Thanks for the help! It works Flawlessly! I'll use it for whenever I want to test my game and I'll use
```
#ifdef WIN32
    FileUtils::getInstance()->addSearchPath("Resources");
#endif
```
For whenever I want to release the game. Much love <3
