### ISSUE TITLE
[PROPOSAL] Change class name `Sprite3D` to `MeshRenderer`

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#688]
I think that the name `Sprite3D` is unclear because it means a sprite in 3d space and not actually a 3d model being rendered and that's what got me and multiple people in the cocos forums confused, Don't you think the name of the node should be `MeshRenderer` or `ModelRenderer` or something else as to make it clear?

**Comment by halx99** [comment]
I prefer MeshRenderer

**Comment by solan-solan** [comment]
If I may, some meanings about this fix.
Cocos2d has decade time of developing, with stable well known api. Potentially it could relatively light to go from cocos2d to adxe, for guys who used to use it, since it does not supported any more.
Of cause adxe is more deep fork, which brings more own features. But do you really have something about 3d space rendering support in your roadmap in the near future?
If not, then such changes gives no more then some cosmetic/logical iproves with much bigger pain to customize existing projects. These changes good after quality step, otherwise they looks like hasty.

**Comment by halx99** [comment]
Use `typedef` to mark old name deprecated maybe better

**Comment by solan-solan** [comment]
filenames were changed also

**Comment by solan-solan** [comment]
User can include Sprite3D.h if he desire to extend its behavior for his project, it's c++ after all

**Comment by halx99** [comment]
That also easy to solve it， create a empty file named Sprite3D.h in folder 3d and add one line code to include ccmeshrenderer.h

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by solan-solan** [comment]
Ok, thanks for advise, I will do (material 3d is needed also for me)

I only wanted to notice, that everything is good when it is in time :) , now there were no visible reasons for such deviations from cocos api (imho of course)

**Comment by halx99** [comment]
Do you work for `https://github.com/solan-solan/HeightMap`, I can help you

**Comment by solan-solan** [comment]
This is example of using some technics, which I use in my more bigger project which supposed to be like rpg/action game in openworld (no so big like AAA projects of course, but it should include adventure/fight/quest/dialogs). The example includes postprocessing implementation base on render to texture which is provided by adxe/cocos and base building of 3d world space. It should represented that adxe/cocos are good choice for simple 3d games which are more interesting to my like.
And now, since cocos is not supported, I hope more on adxe engine.
I see how busy you are on engine support.
What help do you mean? I believe, that I can fix my things, but it happened a little unexpected

**Comment by halx99** [comment]
Now your demo project will works with latest `adxe` after merge the PR: https://github.com/solan-solan/HeightMap/pull/1

**Comment by halx99** [comment]
I create a new PR for you: https://github.com/solan-solan/HeightMap/pull/2

![image](https://user-images.githubusercontent.com/6977319/177371991-837eb181-ee04-4322-9550-2a044d66ac58.png)

**Comment by DelinWorks** [comment]
@solan-solan Your game can perform better if you use mesh instancing, this feature is not yet in the engine but I will implement it, the grass on the ground is rendered in a single mesh which nice and fast but also destructive, because If you were to change the position or animate a single blade of grass you would have to send the entire vertex data to the gpu again. But with instancing you could render these grass objects separately with their own nodes and if their material is the same (which it is) they are gonna be rendered using `glDrawElementsInstanced` rather than stuffing all these grass vertices in a mesh.

I might've not explained it very will but this article goes over how to do it: https://learnopengl.com/Advanced-OpenGL/Instancing

**Comment by solan-solan** [comment]
It would be greate!

**Comment by DelinWorks** [comment]
> It would be greate! But as I properly understand it is not a GLES2 decision?

No unforunetly not I just realized

![image](https://user-images.githubusercontent.com/45469625/177409078-a2c0c4e5-570c-4b0e-8335-e017316c3b60.png)
