### ISSUE TITLE
[BUG] Fix extension rebuilding

### ISSUE THREAD

**Issue by DelinWorks** [adxeproject/adxe#701]
I use Visual Studio 2022 and When I modify `adxe` source files the extensions cocostudio, DragonBones... etc get rebuilt too, A solution I have found is to build the extension projects manually once and then unload the extension projects. This bug makes it take too long for the engine to compile after a small change because the extensions get compiled too even though their source files haven't been touched.

**Comment by aismann** [comment]
Maybe a wrong compiler flag (or a missing one)?

**Comment by rh101** [comment]
> I use Visual Studio 2022 and When I modify `adxe` source files the extensions cocostudio, DragonBones... etc get rebuilt too,

Which files are you modifying, because I can't reproduce it the issue in VS2022.  I just tested it by modifying a several `CC***.cpp`  source files in the engine core folder, and it only built those cpp files and nothing else.  If any specific CPP files are triggering a re-build of unrelated files, then that would be an issue.

If you change header files, then that is going to trigger a rebuild of anything that includes those headers at any part of the chain, which in this case is not a bug, and there is nothing that can be done about that.

**Comment by DelinWorks** [comment]
Yeah modifying `.h` files triggers builds for extensions too which kinda sucks 😕 and there is no workaround for it except for the workaround I've mentioned above.
